export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";

export const ADD_TO_WATCHLIST_REQUEST = "ADD_TO_WATCHLIST_REQUEST";
export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAILURE = "ADD_TO_WATCHLIST_FAILURE";
